highlighter: pygments
baseurl: /alibuild
menu_header: ALIBUILD
menu:
  - name: quick.html
    label: QUICKSTART
  -
    name: user.html
    label: USER MANUAL
  -
    name: extra.html
    label: EXTRA TOOLS
  - 
    name: reference.html
    label: REFERENCE
  -
    name: support.html
    label: SUPPORT
defaults: 
  -
    scope:
      path: "basic/"
      type: "posts"
    values:
      category: "basic"
      layout: "main"
